export const links = [
  {
    url: "#home",
    text: "Accueil.",
  },
  {
    url: "#projects",
    text: "Projets.",
  },
  {
    url: "#contact",
    text: "Contact.",
  },
];

export const projects = {
  title: "Liste des projets.",
  items: [
    {
      id: 1,
      img: "img1.png",
      num: "01",
      url: "https://disneyplus-app.vercel.app/",
      urlGit: "https://github.com/ZeAmine/react-disneyplus-app",
      title: "Clone Disney+.",
      text: "Clone de la célèbre plateforme de streaming: Disney+.",
      language: "REACT.JS · TMDB API · AXIOS",
      direction: "reverse",
    },
    {
      id: 2,
      img: "img2.png",
      num: "03",
      url: "https://aiirbnb.vercel.app/",
      urlGit: "https://github.com/ZeAmine/react-airbnb-app",
      title: "Clone Airbnb.",
      text: "Clone de la célèbre plateforme de location de logement: Airbnb.",
      language: "REACT.JS · TAILWIND CSS",
    },
    {
      id: 3,
      img: "img3.png",
      num: "04",
      url: "https://awake-koala.vercel.app/",
      urlGit: "https://github.com/ZeAmine/awake-koala",
      title: "Awake Koala.",
      text: "Site de streaming vous proposant une liste de films bien précis grâce aux multiples filtres intégré.",
      language: "REACT.JS · TMDB API · AXIOS",
      direction: "reverse",
    },
    {
      id: 5,
      img: "img4.png",
      num: "05",
      url: "https://roots-production.netlify.app/",
      urlGit: "https://github.com/ZeAmine/roots-production",
      title: "Roots.",
      text: "Site permettant la propulsion d'artiste peut connu grâce à un system de vote ouvert au public.",
      language: "REACT.JS · TYPESCRIPT · AXIOS · API SPOTIFY",
    },
    {
      id: 6,
      img: "img5.png",
      num: "06",
      url: "https://eclipse-one.vercel.app/",
      urlGit: "https://eclipse-one.vercel.app/",
      title: "Eclipse.",
      text: "Site de présentation d'un produit fictif basé sur un projet de Design Fiction.",
      language: "HTML · CSS · JAVASCRIPT",
      direction: "reverse",
    },
    {
      id: 7,
      img: "img5.png",
      num: "BONUS 01",
      title: "Affiche Eclipse.",
      text: "1er conception graphique, basé sur un projet de Design Fiction.",
      language: "PHOTOSHOP · ILLUSTRATOR",
    },
    {
      id: 8,
      img: "img5.png",
      num: "BONUS 02",
      title: "Affiche Eclipse.",
      text: "2e conception graphique, basé sur un projet de Design Fiction.",
      language: "PHOTOSHOP · ILLUSTRATOR",
      direction: "reverse",
    },
  ],
  urlPrefix: "/assets/imgs/",
};
